# Site
name: "Joanna Blüm Studio"
title: "Joanna Blüm Studio"
description: "Hello! I'm Joanna, and I design, create patterns, and sew! Currently a grad student researching apparel design and Human-Computer Interaction (HCI) 💗"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'G-B0WPY45W4X'
disqus: 'joannablumstudio'
mailchimp-list: 'https://joannablumstudio.us21.list-manage.com/subscribe/post?u=90c73bfd965951d110c9e34d1&amp;id=c4724fec01&amp;f_id=004ae9e6f0'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  joanna:
    name: Joanna
    display_name: Joanna
    avatar: 'assets/images/avatar.png'
    email: joannablumstudio@gmail.com
    web: https://www.joannablumstudio.com
    instagram: https://www.instagram.com/joannablumstudio
    description: "Hey there! I'm Joanna, and I love everything pink! 💗"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-1443804967712837"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
